// SPDX-FileCopyrightText: 2026 Linus Jahn <lnj@kaidan.im>
//
// SPDX-License-Identifier: LGPL-2.1-or-later

#ifndef QXMPPNAMESPACES_H
#define QXMPPNAMESPACES_H

#include "QXmppGlobal.h"

#include <optional>

#include <QString>

namespace QXmpp {

// New namespaces must only be appended, the values are part of the ABI.
enum class Namespace {
    Xml,
    Pie0,
    Stream,
    Client,
    Server,
    Roster,
    Tls,
    Sasl,
    Bind,
    StreamError,
    Session,
    Stanza,
    PreApproval,
    RosterVersioning,
    Rpc,
    FeatureNegotiation,
    LegacyOpenPgp,
    DiscoInfo,
    DiscoItems,
    ExtendedAddressing,
    Muc,
    MucAdmin,
    MucOwner,
    MucUser,
    MucRoomInfo,
    MucRequest,
    MucRoomConfig,
    Ibb,
    Bookmarks,
    PrivateXmlStorage,
    VCard,
    Rsm,
    PubSub,
    PubSubAutoCreate,
    PubSubConfigNode,
    PubSubConfigNodeMax,
    PubSubCreateAndConfigure,
    PubSubCreateNodes,
    PubSubErrors,
    PubSubEvent,
    PubSubMultiItems,
    PubSubNodeConfig,
    PubSubOwner,
    PubSubPublish,
    PubSubPublishOptions,
    PubSubRsm,
    Bytestreams,
    OutOfBandData,
    Xhtml,
    XhtmlIm,
    Register,
    RegisterFeature,
    Auth,
    AuthFeature,
    Geoloc,
    GeolocNotify,
    UserAvatarData,
    UserAvatarMetadata,
    ChatStates,
    LegacyDelayedDelivery,
    SoftwareVersion,
    DataForms,
    StreamInitiation,
    StreamInitiationFileTransfer,
    UrlData,
    Activity,
    Capabilities,
    Tune,
    TuneNotify,
    Archive,
    Compress,
    CompressFeature,
    RosterNotes,
    VCardUpdate,
    ContactAddresses,
    Captcha,
    Jingle1,
    JingleRawUdp1,
    JingleIceUdp1,
    JingleErrors1,
    JingleRtp1,
    JingleRtpAudio,
    JingleRtpVideo,
    JingleRtpInfo1,
    JingleRtpErrors1,
    MessageReceipts,
    Blocking,
    StreamManagement3,
    Ping,
    EntityTime,
    DelayedDelivery,
    ExternalServiceDiscovery2,
    ServerDialback,
    MediaElement,
    Attention0,
    BitsOfBinary,
    DirectMucInvitation,
    Thumbnails1,
    Muji0,
    Carbons2,
    Moved1,
    JingleRtcpFeedback0,
    JingleRtpHeaderExtensions0,
    Forwarding0,
    Hashes2,
    MucUnique,
    MessageCorrection0,
    Mam2,
    Idle1,
    JingleDtls0,
    ChatMarkers0,
    MessageProcessingHints,
    Csi0,
    JingleMessage0,
    Push0,
    StanzaId0,
    HttpUpload0,
    Otr0,
    MessageAttaching1,
    MixCore1,
    MixCore1CreateChannel,
    MixCore1Searchable,
    MixNodesInfo,
    MixNodesMessages,
    MixNodesParticipants,
    OpenPgp0,
    Reporting1,
    Eme0,
    Spoiler0,
    LegacyOmemo,
    Omemo1,
    Omemo2,
    Omemo2Bundles,
    Omemo2Devices,
    Bind2_0,
    Sasl2_2,
    Bookmarks2_1,
    MixNodesPresence,
    MixNodesJidMap,
    MixPam2,
    MixPam2Archive,
    MixRoster0,
    MixPresence0,
    MixAdmin0,
    MixNodesAllowed,
    MixNodesBanned,
    MixNodesConfig,
    MixMisc0,
    MucSelfPingOptimization,
    OccupantId0,
    MessageRetract1,
    MessageRetract1Tombstone,
    MessageModerate1,
    Fallback0,
    TrustMessages1,
    Reactions0,
    FileMetadata0,
    StatelessFileSharing0,
    EncryptedStatelessFileSharing0,
    Atm1,
    Reply0,
    CallInvites0,
    Fast0,
};

QXMPP_EXPORT QString namespaceUri(Namespace ns);
QXMPP_EXPORT std::optional<Namespace> namespaceFromUri(QStringView uri);

}  // namespace QXmpp

#endif  // QXMPPNAMESPACES_H
